name: Deploy Test GCP

on:
    push:
        branches:
            - "master"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Deploy to Server
              uses: appleboy/ssh-action@master
              with:
                  host: 34.125.175.246
                  username: berylmalikaveta
                  key: ${{ secrets.PRIVATE_KEY }}
                  port: 22
                  script: |
                      cd /home/berylmalikaveta/challange-platinum
                      git fetch --all
                      git pull origin master
                      pm2 restart all
